### PR TITLE
Fix for hidden character issue in spec, blocking error for Students

### PR DESCRIPTION
**Pull request by barnes7td**
Please Approve quickly!!!

### CODE REVIEW

**Comment by robmadden** [comment]
# Blync Deploy!

**Comment by robmadden** [comment]
Note: Blync wont' actually deploy anything here since we only touched the `spec.rb` file due to the way we initially built it (we can change this, but it's what we agreed upon). We'll have to deploy this by hand.

**Comment by barnes7td** [comment]
@robmadden It's fixed through the Admin interface also, so no deploy is needed

**Comment by robmadden** [comment]
@barnes7td 👍  I also updated "Blync", the program which does out automatic content delivery, so that it won't post erroneous "Blync Deploy!" comments like the one above if nothing is deployed (this was an edge case).

**Pull request merged**
