### PR TITLE
Fixed method name 'include' and added method 'join'

### PR DESCRIPTION
**Pull request by philspitler**

### CODE REVIEW

**Comment by barnes7td** [comment]
The only change I would want to make is the added String method be grouped with the other String methods. That stuff just bothers me. Otherwise, I approve.

**Comment by philspitler** [comment]
That was my mistake @barnes7td.  It's an Array method.

**Comment by mikesjewett** [comment]
Thanks @philspitler 👍

**Comment by getaaron** [comment]
I agree with @mikesjewett.

**Comment by devtheory** [comment]
That's my default position

https://www.customink.com/designs/iagreewith/rcx0-00b2-p8t2/share?pc=EMAIL-40778&utm_campaign=shared%20design&utm_source=share%20link&utm_medium=shared%20design&utm_content=shared%20desktop

**Pull request merged**
